name: Go

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod download

      - name: install
        run: go install github.com/goreleaser/goreleaser/v2@latest

      - name: Run CI
        run: make ci
